// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PlayerDataBase.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251209143707_AddTargetHistoryStats")]
    partial class AddTargetHistoryStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerScoreboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HighestBountyCollected")
                        .HasColumnType("int");

                    b.Property<string>("MostShotTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetsTakenOut")
                        .HasColumnType("int");

                    b.Property<int>("TotalBountyCollected")
                        .HasColumnType("int");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("TotalShots")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerScoreboards");
                });

            modelBuilder.Entity("PlayerTargetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerScoreboardId")
                        .HasColumnType("int");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimesShot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerScoreboardId");

                    b.ToTable("PlayerTargetHistories");
                });

            modelBuilder.Entity("PlayerTargetHistory", b =>
                {
                    b.HasOne("PlayerScoreboard", "Player")
                        .WithMany("TargetHistory")
                        .HasForeignKey("PlayerScoreboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PlayerScoreboard", b =>
                {
                    b.Navigation("TargetHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
